# Configures for Sidekiq.
---
:verbose: true
:pidfile: ./tmp/pids/sidekiq.pid
:concurrency: 5
:queues:
  - [often, 7]
  - [default, 5]
  - [seldom, 3]
production:
  :concurrency: 20
  :verbose: false
  :logfile: ./log/sidekiq.log
